---
title: "3. Computing"
author: "Alvin Lin"
date: "2017年11月9日"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
## 3.1. Math
```{r}
x <- 100
y <- 400

x + y
```
```{r}
x - y
```
```{r}
x * y
```
```{r}
x / y
```
```{r}
sqrt(x)
```
```{r}
x^2
```
```{r}
log(x)
```

## 3.2. Basic Statistics
```{r}
head(iris)
```
```{r}
# Descriptive statistics
min(iris$Sepal.Length)
```
```{r}
max(iris$Sepal.Length)
```
```{r}
range(iris$Sepal.Length)
```
```{r}
sum(iris$Sepal.Length)
```
```{r}
mean(iris$Sepal.Length)
```
```{r}
median(iris$Sepal.Length)
```
```{r}
quantile(iris$Sepal.Length)
```
```{r}
summary(iris$Sepal.Length)
```
```{r}
# Data trasformation
iris$log.Sepal.Length <- log(iris$Sepal.Length)
head(iris)
```
```{r}
iris$dev <- iris$Sepal.Length - mean(iris$Sepal.Length)
iris$dev.sq <- iris$dev^2
head(iris)
```
```{r}
# Variance 變異數
sum(iris$dev.sq)/(nrow(iris)-1)
```
```{r}
var(iris$Sepal.Length)
```
```{r}
# Standard deviation 標準差
sqrt(sum(iris$dev.sq)/(nrow(iris)-1))
```
```{r}
sqrt(var(iris$Sepal.Length))
```
```{r}
sd(iris$Sepal.Length)
```
```{r}
# Linear Regression 簡單線性迴歸
lm(Petal.Width ~ Petal.Length, data=iris)
```
```{r}
summary(lm(Petal.Width ~ Petal.Length, data=iris))
```

