---
title: "4. Data analysis 101：綜合演練"
author: "Alvin Lin"
date: "2017年11月9日"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## 4.1. R very very quick review
```{r}
# a typical table format data
head(iris)
```

```{r}
# [TRY] head(iris, 20)
tail(iris)
```

```{r}
# Dimensions
dim(iris)
```

```{r}
nrow(iris)
```

```{r}
length(iris)
```

```{r}
names(iris)
```

```{r}
# 看資料欄位想故事
str(iris)
```

```{r}
summary(iris)
```

```{r}
# slice
iris[4,] # 第 4 列
```

```{r}
iris[,2] # 第 2 欄
```

```{r}
iris[4,2] 
```
```{r}
iris[4,"Sepal.Width"]
```
### Quiz: 請嘗試比較兩程式碼者有何不同: 
iris[c(2:4),]　
iris[c(2,4),]
```{r}
iris[c(2:4),]　
iris[c(2,4),]
```

## 4.2. Conditional slice
```{r}
which(iris$Species == "versicolor")
```
```{r}
iris[which(iris$Species == "versicolor"),]
```

### Quiz: 請嘗試找出 “versicolor”, Petal.Length > 4 的資料
```{r}
iris[which(iris$Species=="versicolor" & iris$Petal.Length>4),]
```

## 4.3. 寫入資料
利用read.table讀檔，利用write.table輸出檔案
```{r}
# write to a file
write.table(iris, file = 'iris.csv',sep=',')

# or, more concisely:
write.csv(iris, file = 'iris.csv')
```

## 4.4. 讀取資料
```{r}
data <- read.table(file = 'iris.csv', header = TRUE, sep=',')

# or, more concisely:
data <- read.csv(file = 'iris.csv')

# if you don't want to type in the path
data <- read.table(file = file.choose(), sep=',')
```



# 本日目標
- 請讀入您本次課程所需要的分析資料
    - read.table() / read.csv()
    - ?read.table() for more information


